name = "AUDL Modded MC"
author = "HyloArch"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da81518808351de901342a50b69f1b49beeb771c8cd922b12697d28a6cbaf1d1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
